### PR TITLE
Monkey patch meteor collections

### LINKED ISSUE #29: Incompatibility with meteor-stub-collections when stubbing Meteor.users
I've lately seen that I started out having problems with my tests on the client-side. It shows, that every time I try to create a stub of the collection `Meteor.users` by using the package `meteor-stub-collections`, I get the following error:

```
Error: use "new" to construct a Mongo.Collection
    at ns.Collection.Mongo.Collection (packages/mongo.js?hash=90f037f47abee1e74ba80360e6b3f3dbaa792260:113:50)
    at new ns.Collection (packages/matb33_collection-hooks.js?hash=d44fd0eb02806747e1bb0bdc3938463e415c63ec:284:27)
    at packages/hwillson_stub-collections.js?hash=bef58d9f36ab39205e53f7e1fffa813805568f78:80:28
    at Array.forEach (native)
    at Object.publicApi.stub (packages/hwillson_stub-collections.js?hash=bef58d9f36ab39205e53f7e1fffa813805568f78:74:35)
    at Context.<anonymous> (app/app.js?hash=6db509560fea1b6fa4bd95b4897829e3a9148f6c:9987:48)
    at callFn (packages/practicalmeteor_mocha-core.js?hash=6ff455cf7e5c128f88197d5d8c9244271a433d12:4346:21)
    at Hook.Runnable.run (packages/practicalmeteor_mocha-core.js?hash=6ff455cf7e5c128f88197d5d8c9244271a433d12:4339:7)
    at next (packages/practicalmeteor_mocha-core.js?hash=6ff455cf7e5c128f88197d5d8c9244271a433d12:4685:10)
    at packages/practicalmeteor_mocha-core.js?hash=6ff455cf7e5c128f88197d5d8c9244271a433d12:4707:5
```

Have you seen this before? Do you know where this is originated from?

### PR DESCRIPTION
**Pull request by SimonSimCity**
Fixes #29

### CODE REVIEW

**Comment by mikowals** [comment]
Thanks for the pull request! I have seen it and the related issues and will try to have a look at it this weekend.

**Comment by SimonSimCity** [comment]
Have you had time for this? :wink: I'm as of now running a self-patched version and would really like to get back to the main stream.

**Comment by SimonSimCity** [comment]
@mikowals have you had any time yet to take a closer look at it?

**Comment by SimonSimCity** [comment]
Have you now had time to look at it? Quite some months passed without any activity, so I thought it would be good bringing it up again ...

I use this code in production already and haven't had a single problem with it.

**Comment by SimonSimCity** [comment]
@mikowals Any update? I've used it all these days now in production without any issues.

**Pull request merged**
